name: sample-django
services:
- name: server
  github:
    repo: digitalocean/sample-django
    branch: static
    deploy_on_push: true
  run_command: gunicorn --worker-tmp-dir /dev/shm mysite.wsgi
  envs:
  - key: DISABLE_COLLECTSTATIC
    value: "1"
    scope: BUILD_TIME
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"
    scope: RUN_TIME
  - key: DJANGO_ALLOWED_HOSTS
    value: "${APP_DOMAIN}"
    scope: RUN_TIME
jobs:
- name: migrate
  kind: PRE_DEPLOY
  github:
    repo: digitalocean/sample-django
    branch: static
    deploy_on_push: true
  run_command: python manage.py migrate
  envs:
  - key: DISABLE_COLLECTSTATIC
    value: "1"
    scope: BUILD_TIME
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"
    scope: RUN_TIME
